# Importing data and libraries.

In [245]:
import pandas as pd
import numpy as np

In [246]:
data_raw=pd.read_csv('/content/data_num.csv',index_col=0)
data_raw

,Age,Pclass,SibSp,Parch,Fare,Sex,Embarked Cherbourg,Embarked Queenstown,Embarked Southampton,Crew,Royal,Married women,Single women,Heir,Men,Survived,Name
0,22.0,3,1,0,7.2500,0,0,0,1,0,0,0,0,0,1,0.0,"Braund, Mr. Owen Harris"
1,38.0,1,1,0,71.2833,1,1,0,0,0,0,1,0,0,0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,26.0,3,0,0,7.9250,1,0,0,1,0,0,0,1,0,0,1.0,"Heikkinen, Miss. Laina"
3,35.0,1,1,0,53.1000,1,0,0,1,0,0,1,0,0,0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,35.0,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,0.0,"Allen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,NaN,"Spector, Mr. Woolf"
1305,39.0,1,0,0,108.9000,1,1,0,0,0,0,0,0,0,0,NaN,"Oliva y Ocana, Dona. Fermina"
1306,38.5,3,0,0,7.2500,0,0,0,1,0,0,0,0,0,1,NaN,"Saether, Mr. Simon Sivertsen"
1307,NaN,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,NaN,"Ware, Mr. Frederick"
1308,NaN,3,1,1,22.3583,0,1,0,0,0,0,0,0,1,0,NaN,"Peter, Master. Michael J"

# Cleaning

Some file cleaning has already been done previously

Dropping items that will not be used in the analysis

In [247]:
data = data_raw.copy()
data.drop(["Name","Survived"],inplace=True,axis=1)
data.dropna(inplace=True)
print(data.isna().sum())
print(len(data))

Age                     0
Pclass                  0
SibSp                   0
Parch                   0
Fare                    0
Sex                     0
Embarked Cherbourg      0
Embarked Queenstown     0
Embarked Southampton    0
Crew                    0
Royal                   0
Married women           0
Single women            0
Heir                    0
Men                     0
dtype: int64
1046

Separating variables, independent variables X and dependent variable y for split and train

In [248]:
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values
print(X,y)

[[3. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 1. 0. 0.]
 ...
 [3. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 1.]] [22.  38.  26.  ... 28.  39.  38.5]

# Split into training & test sets

The data will be separated into four groups

Independent variables:
- X_train: for train the model
- X_test: for prediction

Dependent variables:
- y_train: for train the model
- y_test: for prediction

In [249]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [250]:
np.set_printoptions(threshold=200)
print('---X_train---'*20)
print(X_train)
print('---X_test---'*20)
print(X_test)
print('---y_train---'*20)
print(y_train)
print('---y_test---'*20)
print(y_test)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[1. 0. 0. ... 0. 0. 1.]
 [3. 1. 0. ... 0. 0. 1.]
 [3. 4. 2. ... 0. 1. 0.]
 ...
 [3. 0. 0. ... 0. 0. 1.]
 [3. 1. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 0. 0.]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[3. 0. 0. ... 0. 0. 1.]
 [3. 0. 0. ... 0. 0. 1.]
 [3. 0. 0. ... 1. 0. 0.]
 ...
 [2. 0. 0. ... 1. 0. 0.]
 [2. 1. 0. ... 0. 0. 1.]
 [2. 0. 0. ... 0. 0. 0.]]
---y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train---
[27.  23.   9.  ... 60.5 26.  45. ]
---y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test---
[23. 32. 18. ... 24. 44. 23.]

#Scaling


.fit() Calculate the mean and standard deviation to use on transform(), and store the values in the StandardScaler() class instance, in this case in the variable sc

.transform() perform standardization by the following formula:
$\mathrm{x}_{standardization}^{}=\frac{x-mean}{standard\text{ }deviation}$

----------------------------

print(sc.mean_) to see the mean 

print(sc.var_) to see the variance

print(np.sqrt(sc.var_)) or print(sc.scale_) to see the standard deviation

-----------------------------

The dummy variables aren't standardized because they are already between 0 and 1

----------------------------

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

From https://www.atoti.io/articles/when-to-perform-a-feature-scaling/ about scaling in linear regressions:

"Technically, feature scaling does not make a difference in the regression, but it might give us some practical benefits and in further feature engineering steps."

In [251]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:-10] = sc.fit_transform(X_train[:,:-10])
X_test[:,:-10] = sc.transform(X_test[:,:-10])

In [252]:
print('---X_train---'*20)
print(X_train)
print('---X_test---'*20)
print(X_test)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[-1.46 -0.54 -0.49 ...  0.    0.    1.  ]
 [ 0.92  0.58 -0.49 ...  0.    0.    1.  ]
 [ 0.92  3.92  1.96 ...  0.    1.    0.  ]
 ...
 [ 0.92 -0.54 -0.49 ...  0.    0.    1.  ]
 [ 0.92  0.58 -0.49 ...  0.    0.    1.  ]
 [-1.46  0.58  0.73 ...  0.    0.    0.  ]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[ 0.92 -0.54 -0.49 ...  0.    0.    1.  ]
 [ 0.92 -0.54 -0.49 ...  0.    0.    1.  ]
 [ 0.92 -0.54 -0.49 ...  1.    0.    0.  ]
 ...
 [-0.27 -0.54 -0.49 ...  1.    0.    0.  ]
 [-0.27  0.58 -0.49 ...  0.    0.    1.  ]
 [-0.27 -0.54 -0.49 ...  0.    0.    0.  ]]

# Modelling

## Build the model

Instantiate the object with the name regressor as a model, for the machine learning

In [253]:
from pandas.core.accessor import register_dataframe_accessor
from sklearn.linear_model import LinearRegression
from sklearn import linear_model

parameters = {'copy_X': True, 'fit_intercept': True, 'n_jobs': 0, 'positive': False}

#** send the value of dict to the function
regressor = LinearRegression(**parameters)

## Train the model

Train the model on classifier object, with X_train and y_train

In [254]:
regressor.fit(X_train, y_train)

LinearRegression(n_jobs=0)

## Make predictions

Predictions for dependent variables with the trained model

Prediction for the vector X_test

In [255]:
prediction = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(prediction)

[28.15 28.16 16.97 ... 23.19 33.11 45.42]

# Evaluation

 R²(coefficient of determination) regression score function.

Best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). In the general case when the true y is non-constant, a constant model that always predicts the average y disregarding the input features would get a R² score of 0.0.

Source: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html

In [256]:
from sklearn.metrics import r2_score
r2_score(y_test, prediction)

0.29724931373894947

##Calculating the best parameter for the model

Shows every parameter that could be use on GridSearchCV for this kind of machine learning

In [257]:
print(LinearRegression().get_params().keys())

dict_keys(['copy_X', 'fit_intercept', 'n_jobs', 'normalize', 'positive'])

GridSearchCV calculates the best parameter for the model.

First you calculate using GridSearchCV, then use the values on your model, lastly you disable the algorithm of GridSearchCV by commenting

It could be divided in parts because it is time expensive

In [258]:
#Calculating the best model possible
# This code could take a long time, uncoment to run the full GridSearchCV
'''
from sklearn.model_selection import GridSearchCV 

#Parameters
# 1° attempt Best result: 0.420858 using {'copy_X': True, 'fit_intercept': True, 'n_jobs': 0, 'positive': False}
parameters = {'copy_X':[True, False],'fit_intercept':[True,False],'n_jobs':list(range(0, 20)),'positive':[True,False]}

#GridSearchCV
estimator = LinearRegression()
grid = GridSearchCV(estimator,parameters, cv=None)
grid.fit(X_train, y_train)
print("Best result: %f using %s" % (grid.best_score_, grid.best_params_))
'''

'\nfrom sklearn.model_selection import GridSearchCV \n\n#Parameters\n# 1° attempt Best result: 0.420858 using {\'copy_X\': True, \'fit_intercept\': True, \'n_jobs\': 0, \'positive\': False}\nparameters = {\'copy_X\':[True, False],\'fit_intercept\':[True,False],\'n_jobs\':list(range(0, 20)),\'positive\':[True,False]}\n\n#GridSearchCV\nestimator = LinearRegression()\ngrid = GridSearchCV(estimator,parameters, cv=None)\ngrid.fit(X_train, y_train)\nprint("Best result: %f using %s" % (grid.best_score_, grid.best_params_))\n'