# Importing data and libraries.

In [53]:
import pandas as pd
import numpy as np

In [54]:
data_raw=pd.read_csv('/content/data_num.csv',index_col=0)
data_raw

,Age,Pclass,SibSp,Parch,Fare,Sex,Embarked Cherbourg,Embarked Queenstown,Embarked Southampton,Crew,Royal,Married women,Single women,Heir,Men,Survived,Name
0,22.0,3,1,0,7.2500,0,0,0,1,0,0,0,0,0,1,0.0,"Braund, Mr. Owen Harris"
1,38.0,1,1,0,71.2833,1,1,0,0,0,0,1,0,0,0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,26.0,3,0,0,7.9250,1,0,0,1,0,0,0,1,0,0,1.0,"Heikkinen, Miss. Laina"
3,35.0,1,1,0,53.1000,1,0,0,1,0,0,1,0,0,0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,35.0,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,0.0,"Allen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,NaN,"Spector, Mr. Woolf"
1305,39.0,1,0,0,108.9000,1,1,0,0,0,0,0,0,0,0,NaN,"Oliva y Ocana, Dona. Fermina"
1306,38.5,3,0,0,7.2500,0,0,0,1,0,0,0,0,0,1,NaN,"Saether, Mr. Simon Sivertsen"
1307,NaN,3,0,0,8.0500,0,0,0,1,0,0,0,0,0,1,NaN,"Ware, Mr. Frederick"
1308,NaN,3,1,1,22.3583,0,1,0,0,0,0,0,0,1,0,NaN,"Peter, Master. Michael J"

# Cleaning

Some file cleaning has already been done previously

Dropping items that will not be used in the analysis

In [55]:
data = data_raw.copy()
data.drop(["Name","Survived"],inplace=True,axis=1)
data.dropna(inplace=True)
print(data.isna().sum())
print(len(data))

Age                     0
Pclass                  0
SibSp                   0
Parch                   0
Fare                    0
Sex                     0
Embarked Cherbourg      0
Embarked Queenstown     0
Embarked Southampton    0
Crew                    0
Royal                   0
Married women           0
Single women            0
Heir                    0
Men                     0
dtype: int64
1046

Separating variables, independent variables X and dependent variable y for split and train

In [56]:
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values
print(X,y)

[[3. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 1. 0. 0.]
 ...
 [3. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 1.]] [22.  38.  26.  ... 28.  39.  38.5]

Reshape y for scaling

In [57]:
y = y.reshape(len(y),1)

#Scaling


.fit() Calculate the mean and standard deviation to use on transform(), and store the values in the StandardScaler() class instance, in this case in the variable sc

.transform() perform standardization by the following formula:
$\mathrm{x}_{standardization}^{}=\frac{x-mean}{standard\text{ }deviation}$

----------------------------

print(sc.mean_) to see the mean 

print(sc.var_) to see the variance

print(np.sqrt(sc.var_)) or print(sc.scale_) to see the standard deviation

-----------------------------

The dummy variables aren't standardized because they are already between 0 and 1

----------------------------

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In this SVR we will be scaling first, because we will performace the scaling in y too

In [58]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X[:,:-10] = sc_X.fit_transform(X[:,:-10])
y = sc_y.fit_transform(y)

In [59]:
print('---X_train---'*20)
print(X)
print('---X_test---'*20)
print(y)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[ 0.94227606  0.54526153 -0.50116236 ...  0.          0.
   1.        ]
 [-1.43557861  0.54526153 -0.50116236 ...  0.          0.
   0.        ]
 [ 0.94227606 -0.55155301 -0.50116236 ...  1.          0.
   0.        ]
 ...
 [ 0.94227606 -0.55155301 -0.50116236 ...  1.          0.
   0.        ]
 [-1.43557861 -0.55155301 -0.50116236 ...  0.          0.
   0.        ]
 [ 0.94227606 -0.55155301 -0.50116236 ...  0.          0.
   1.        ]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[-0.54705043]
 [ 0.56355152]
 [-0.26939994]
 ...
 [-0.1305747 ]
 [ 0.63296414]
 [ 0.59825783]]

# Split into training & test sets

The data will be separated into four groups

Independent variables:
- X_train: for train the model
- X_test: for prediction

Dependent variables:
- y_train: for train the model
- y_test: for prediction

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [61]:
np.set_printoptions(threshold=200)
print('---X_train---'*20)
print(X_train)
print('---X_test---'*20)
print(X_test)
print('---y_train---'*20)
print(y_train)
print('---y_test---'*20)
print(y_test)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[-1.43557861 -0.55155301 -0.50116236 ...  0.          0.
   1.        ]
 [ 0.94227606  0.54526153 -0.50116236 ...  0.          0.
   1.        ]
 [ 0.94227606  3.83570514  1.88163685 ...  0.          1.
   0.        ]
 ...
 [ 0.94227606 -0.55155301 -0.50116236 ...  0.          0.
   1.        ]
 [ 0.94227606  0.54526153 -0.50116236 ...  0.          0.
   1.        ]
 [-1.43557861  0.54526153  0.69023725 ...  0.          0.
   0.        ]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[ 0.94227606 -0.55155301 -0.50116236 ...  0.          0.
   1.        ]
 [ 0.94227606 -0.55155301 -0.50116236 ...  0.          0.
   1.        ]
 [ 0.94227606 -0.55155301 -0.50116236 ...  1.          0.
   0.        ]
 ...
 [-0.24665127 -0.55155301 -0.50116236 ...  1.          0.
   0.        ]
 [-0.24665127  0.54526153 -0.50116236 ...  0.          0.
   1.        ]
 [-0.24665127 -0.55155301 -0.50116236 ...  0.          0.
   0.        ]]
---y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train---
[[-0.19998732]
 [-0.47763781]
 [-1.44941451]
 ...
 [ 2.12533551]
 [-0.26939994]
 [ 1.04943987]]
---y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test------y_test---
[[-0.47763781]
 [ 0.14707579]
 [-0.82470092]
 ...
 [-0.40822519]
 [ 0.98002725]
 [-0.47763781]]

# Modelling

## Build the model

Instantiate the object with the name regressor as a model, for the machine learning

In [62]:
from sklearn.svm import SVR
parameters = {'C': 1, 'coef0': 8, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
regressor = SVR(**parameters)

## Train the model

Train the model on classifier object, with X_train and y_train

In [63]:
regressor.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1, coef0=8, degree=2, gamma='auto', kernel='poly')

## Make predictions

Predictions for dependent variables with the trained model

Prediction for the vector X_test

In [64]:
prediction  = sc_y.inverse_transform(regressor.predict(X_test).reshape(-1,1))
prediction

array([[26.44377842],
       [26.4418077 ],
       [20.56747893],
       ...,
       [22.88257101],
       [29.88986564],
       [43.47240536]])

# Evaluation

 R²(coefficient of determination) regression score function.

Best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). In the general case when the true y is non-constant, a constant model that always predicts the average y disregarding the input features would get a R² score of 0.0.

Source: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html

In [65]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), prediction)

0.33745409945384774

##Calculating the best parameter for the model

Shows every parameter that could be use on GridSearchCV for this kind of machine learning

In [66]:
print(SVR().get_params().keys())

dict_keys(['C', 'cache_size', 'coef0', 'degree', 'epsilon', 'gamma', 'kernel', 'max_iter', 'shrinking', 'tol', 'verbose'])

GridSearchCV calculates the best parameter for the model.

First you calculate using GridSearchCV, then use the values on your model, lastly you disable the algorithm of GridSearchCV by commenting

It could be divided in parts because it is time expensive

In [67]:
#Calculating the best model possible
# This code could take a long time, uncoment to run the full GridSearchCV
'''
from sklearn.model_selection import GridSearchCV 

#Parameters
#1° attempt Best result: 0.436060 using {'C': 1, 'coef0': 4, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
parameters = {'kernel' : ('linear', 'poly', 'rbf', 'sigmoid'),'C' :  list(range(1,5,1)),'degree' : list(range(1,5,1)),'coef0': list(range(1,5,1)),'gamma' :('auto','scale')}

#2° attempt Best result: 0.436744 using {'C': 1, 'coef0': 8, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
parameters = {'kernel' : ['poly'],'C' : [1],'degree' : [2],'coef0': list(range(4,15,1)),'gamma' :['auto']}


#GridSearchCV
estimator = SVR()
grid = GridSearchCV(estimator,parameters, cv=None,verbose=3)
grid.fit(X_train, np.ravel(y_train))
print("Best result: %f using %s" % (grid.best_score_, grid.best_params_))
'''

'\nfrom sklearn.model_selection import GridSearchCV \n\n#Parameters\n#1° attempt Best result: 0.436060 using {\'C\': 1, \'coef0\': 4, \'degree\': 2, \'gamma\': \'auto\', \'kernel\': \'poly\'}\nparameters = {\'kernel\' : (\'linear\', \'poly\', \'rbf\', \'sigmoid\'),\'C\' :  list(range(1,5,1)),\'degree\' : list(range(1,5,1)),\'coef0\': list(range(1,5,1)),\'gamma\' :(\'auto\',\'scale\')}\n\n#2° attempt Best result: 0.436744 using {\'C\': 1, \'coef0\': 8, \'degree\': 2, \'gamma\': \'auto\', \'kernel\': \'poly\'}\nparameters = {\'kernel\' : [\'poly\'],\'C\' : [1],\'degree\' : [2],\'coef0\': list(range(4,15,1)),\'gamma\' :[\'auto\']}\n\n\n#GridSearchCV\nestimator = SVR()\ngrid = GridSearchCV(estimator,parameters, cv=None,verbose=3)\ngrid.fit(X_train, np.ravel(y_train))\nprint("Best result: %f using %s" % (grid.best_score_, grid.best_params_))\n'